### ISSUE TITLE
Segformer Model

### ISSUE THREAD

**Issue by SvenDierfeld** [ashutosh1807/Depthformer#2]
Hello ashutosh1807,

may I ask which segformer model you are using? 

So in line 159 in unet_adaptive_bins.py you do this: 
`state_dict = torch.load(os.environ['SEGFORMER_PATH'])`
 
For the models in [here](https://drive.google.com/drive/folders/1GAku0G0iR9DsBxCbfENWMJ27c5lYUeQA) I can see that there are multiple Segformer models. Which one did you use for KITTI?

Greetings

**Comment by ashutosh1807** [comment]
Mit_b4 [link](https://drive.google.com/file/d/1BUtU42moYrOFbsMCE-LTTkUE-mrWnfG2/view?usp=share_link)
