### ISSUE TITLE
How was the gt depth generated?

### ISSUE THREAD

**Issue by SvenDierfeld** [ashutosh1807/Depthformer#3]
Hello ashutosh1807,

do you have a script for generating the ground truth depth? As far as I now it is not supplied by the kitti dataset **(it is!)**.

Greetings

**Comment by SvenDierfeld** [comment]
Also requirements or a docker image would be appreciated.

**Comment by ashutosh1807** [comment]
You can use the following command in evaluate.py
`plt.imsave(pred_path, pred, cmap='plasma')`
